### ISSUE TITLE
Doesn't work in Ubuntu

### ISSUE THREAD

**Issue by jawira** [matco/wheeltab#4]
Hello, your extension doesn't work for me, I'm using Firefox and Ubuntu 20.04

After some research I configured Firefox to switch tabs without you extension: 
https://support.mozilla.org/en-US/questions/1285434

So what if your extension simply changes this value if user is using Firefox ?

Thanks

**Comment by matco** [comment]
Hello!

Thanks for your message.

The goal of the extension is to do something different from the `toolkit.tabbox.switchByScrolling` flag. It allows switching tabs from anywhere in the content of a tab, using a combination of a mouse click and a mouse wheel scroll.

By the way, I removed the extension from the Firefox add-ons website. The version 2 of the extension that was hosted on the store was incompatible with windows managers on Linux (because, on these systems, the contextual menu is displayed directly after the mouse down event instead of after a full mouse click, leaving no time to hook a custom menu), and Firefox does not support the latest version of the extension.

**Comment by jawira** [comment]
Oh, I understand better now. Thank you for your feedback 🤗
